// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBRkA_ozl6B_OL6PVsLN6KWj894HVTzTQ',
    appId: '1:1094845451080:web:d1e4568013652ac839c17d',
    messagingSenderId: '1094845451080',
    projectId: 'red-drop-6db08',
    authDomain: 'red-drop-6db08.firebaseapp.com',
    storageBucket: 'red-drop-6db08.appspot.com',
    measurementId: 'G-J46FNV96Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC21yAqScJEm8g38SuXB8aThbwPyN9vxDE',
    appId: '1:1094845451080:android:8ed5ee453fd0695939c17d',
    messagingSenderId: '1094845451080',
    projectId: 'red-drop-6db08',
    storageBucket: 'red-drop-6db08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQm_-qXdoUI_Z0009KcB6UL4j-hv1U0c',
    appId: '1:1094845451080:ios:7fc2ed33d1a629ef39c17d',
    messagingSenderId: '1094845451080',
    projectId: 'red-drop-6db08',
    storageBucket: 'red-drop-6db08.appspot.com',
    iosBundleId: 'com.example.redDrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcQm_-qXdoUI_Z0009KcB6UL4j-hv1U0c',
    appId: '1:1094845451080:ios:7fc2ed33d1a629ef39c17d',
    messagingSenderId: '1094845451080',
    projectId: 'red-drop-6db08',
    storageBucket: 'red-drop-6db08.appspot.com',
    iosBundleId: 'com.example.redDrop',
  );
}
